services:
  db:
      image: mysql:8
      environment:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: OPK12A
        MYSQL_USER: user
        MYSQL_PASSWORD: password
      ports:
          - "3307:3306"
      volumes:
          - ./db/data:/var/lib/mysql
          - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  app:
      build: .
      ports:
        - "3000:3000"
      environment:
        DB_HOST: db
        DB_USER: user
        DB_PASSWORD: password
        DB_NAME: OPK12A
      depends_on:
        - db
      volumes:
        - ./site:/app

volumes:
    db_data:
